### ISSUE TITLE
Plugins support roadmap

### ISSUE THREAD

**Issue by pauchiner** [pauchiner/pastelnight.nvim#18]
### Here are some popular plugins that have not been configured yet:
- [ ] [barbar.nvim](https://github.com/romgrk/barbar.nvim)
- [ ] [diffview.nvim](https://github.com/sindrets/diffview.nvim)
- [ ] [hop.nvim](https://github.com/phaazon/hop.nvim)
- [ ] [illuminate.vim](https://github.com/RRethy/vim-illuminate)
- [ ] [mini.nvim](https://github.com/echasnovski/mini.nvim)
- [ ] [neogit](https://github.com/NeogitOrg/neogit)
- [ ] [neo-tree.nvim](https://github.com/nvim-neo-tree/neo-tree.nvim)
- [ ] [neotest](https://github.com/nvim-neotest/neotest)
- [ ] [nvim-navic](https://github.com/SmiteshP/nvim-navic)
- [ ] [trouble.nvim](https://github.com/folke/trouble.nvim)
- [ ] [which-key.nvim](https://github.com/folke/which-key.nvim)

Feel free if you want to contribute with a PR, in the meantime I will add these plugins to the theme in my free time, thanks 😄.
